# **ML_2. Supervised Learning**

### **1. Ответь на вопросы**

***i. Выведите аналитическое решение задачи регрессии. Используйте векторную форму уравнения.***  
*Derive an analytical solution to the regression problem. Use a vector form of the equation.*  

$$
\boxed{
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf y
}
$$

---

***ii. Какие изменения произойдут в решении при добавлении L1- и L2-регуляризации к функции потерь?***  
*What changes in the solution when L1 and L2 regularizations are added to the loss function.*  

Регуляризация используется для борьбы с переобучением и уменьшения сложности модели.
Идея состоит в том, чтобы при обучении минимизировать не только ошибку предсказаний, но и дополнительный штраф за слишком большие значения весов.

**Bias (свободный член) обычно не регуляризуется**, поэтому в реализации штраф применяется только к весам признаков.

К исходной функции потерь добавляется регуляризационный штраф $R(\boldsymbol{\beta})$, а итоговая задача оптимизации принимает вид:
$$ \min_{\boldsymbol{\beta}} L_{\text{reg}}(\boldsymbol{\beta}) = \min_{\boldsymbol{\beta}} \Big( L(\boldsymbol{\beta}) + \lambda R(\boldsymbol{\beta}) \Big) $$

* **$L$** — исходная функция потерь (ошибка модели на обучающих данных);
* **$R(\boldsymbol{\beta})$** — регуляризационный штраф, зависящий от вектора весов бета;
* **$\lambda$** — коэффициент (сила) регуляризации. Чем больше $\lambda$, тем сильнее модель штрафуется за величину весов. (в sklean обозначается как $\alpha$ ) 

*в случае L2-регуляризации* (Ridge) штраф = сумме квадратов коэффициентов (квадрат $L_2$-нормы вектора весов):
$$ L_{L2}(\boldsymbol{\beta}) = \|\mathbf{y} - X\boldsymbol{\beta}\|_2^2 + \lambda \|\boldsymbol{\beta}\|_2^2 = \|\mathbf{y} - X\boldsymbol{\beta}\|_2^2 + \lambda \sum_{j=1}^{p} \beta_j^2 $$
* **Изменение в самом решении:** для линейной регрессии задача имеет строгое аналитическое решение в замкнутом виде. Главное изменение — к матрице $X^TX$ добавляется сдвиг $\lambda I$, что делает её гарантированно обратимой и решает проблему мультиколлинеарности:
$$ \hat{\boldsymbol{\beta}}_{L2} = (X^TX + \lambda I)^{-1}X^T\mathbf{y} $$

*в случае L1-регуляризации* (Lasso) штраф = сумме модулей коэффициентов ($L_1$-норма вектора весов):
$$ L_{L1}(\boldsymbol{\beta}) = \|\mathbf{y} - X\boldsymbol{\beta}\|_2^2 + \lambda \|\boldsymbol{\beta}\|_1 = \|\mathbf{y} - X\boldsymbol{\beta}\|_2^2 + \lambda \sum_{j=1}^{p} |\beta_j| $$
* **Изменение в самом решении:** из-за наличия модулей функция потерь становится недифференцируемой в нуле, поэтому аналитического решения в замкнутом виде не существует. Задача решается численными методами оптимизации (например, координатным спуском), а получаемое векторное решение становится разреженным , то есть содержит много весов, строго равных нулю.


---

***iii. Объясните, почему L1-регуляризация часто используется для отбора признаков. Почему после обучения модели остается много весов, равных 0?***   
*Explain why L1 regularization is often used to select features. Why are there many weights equal to 0 after the model is fit?* 

* **Причина зануления весов:** геометрически штраф L1 имеет форму излома (острые вершины в точке $\beta_j = 0$). При минимизации функции потерь линии уровня ошибки чаще всего пересекают ограничения именно на осях координат, где один или несколько коэффициентов **точно равны нулю**.
* **Практический смысл:** веса при слабых, зашумленных или избыточных признаках обнуляются ($\beta_j = 0$), что приводит к автоматическому **отбору признаков** и исключению их из модели. В отличие от L1, регуляризация L2 лишь уменьшает веса, но не делает их строго нулевыми.


---
***iV. Объясните, как можно использовать те же модели (линейная регрессия, гребневая регрессия и т. д.), но при этом обеспечить возможность учета нелинейных зависимостей***  
*Explain how you can use the same models (Linear regression, Ridge, etc.) but make it possible to fit nonlinear dependencies.*

Линейная регрессия линейна **только по параметрам $\boldsymbol{\beta}$**, но не по исходным признакам. Для учета нелинейности применяется **генерация признаков (feature engineering)**:

1. Исходные признаки трансформируются с помощью нелинейных базисных функций $\phi(x)$. 
2. На вход стандартной линейной модели (или Ridge/Lasso) подается новая матрица признаков $\Phi$:
   * **Полиномы:** $x \to (x, x^2, x^3)$
   * **Нелинейные преобразования:** $x \to (\log x, \exp(x), \sin x)$
   * **Взаимодействия:** $(x_1, x_2) \to (x_1, x_2, x_1 x_2)$

Модель находит веса $\boldsymbol{\beta}$ с помощью того же аналитического решения $\hat{\boldsymbol{\beta}} = (\Phi^T\Phi)^{-1}\Phi^T\mathbf{y}$, сохраняя вычислительную простоту, но описывая сложные нелинейные границы.

*What changes in the solution when L1 and L2 regularizations are added to the loss function.*


[Подробные ответы](ML_2_2_Linear_Regression.%20Задание.md)

### **2. Введение**.  
*Выполните всю предварительную обработку данных из предыдущего урока.*

#### ***i. Импорт библиотек***

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings

#### ***ii. Загрузка train и test датасетов. (read train and test parts)***

In [2]:
data_train = pd.read_json("../datasets/train.json")
print(f"""Количество строк: {data_train.shape[0]}
Количество столбцов: {data_train.shape[1]}""")

Количество строк: 49352
Количество столбцов: 15

In [3]:
data_test = pd.read_json("../datasets/test.json")
print(f"""Количество строк: {data_test.shape[0]}
Количество столбцов: {data_test.shape[1]}""")

Количество строк: 74659
Количество столбцов: 14

In [4]:
percentile_1 = data_train["price"].quantile(0.01)
percentile_99 = data_train["price"].quantile(0.99)

data_train = data_train[
    (data_train["price"] > percentile_1) & (data_train["price"] < percentile_99)
].copy()

price_lowest, price_highest = data_train["price"].min(), data_train["price"].max()


data_train["interest_level"] = data_train["interest_level"].map(
    {"low": 0, "medium": 1, "high": 2}
)
data_train.shape

(48343, 15)

In [5]:
data_train_backup = data_train.copy()

In [6]:
data_test = data_test[
    (data_test["price"] >= price_lowest) & (data_test["price"] <= price_highest)
].copy()

bath_max = data_train["bathrooms"].max()
bed_max = data_train["bedrooms"].max()
data_test = data_test[
    (data_test["bathrooms"] <= bath_max) & (data_test["bedrooms"] <= bed_max)
].copy()

data_test.shape

(73175, 14)

### **3. Введение в анализ данных, часть 2**.

#### ***i. Давайте создадим дополнительные характеристики для повышения качества модели. Рассмотрим столбец под названием «Features». Он содержит список основных особенностей текущей квартиры.***

In [7]:
cols = ["bathrooms", "bedrooms", "features"]
data_train[cols].head(10)

    bathrooms  bedrooms                                           features
4         1.0         1  [Dining Room, Pre-War, Laundry in Building, Di...
6         1.0         2  [Doorman, Elevator, Laundry in Building, Dishw...
9         1.0         2  [Doorman, Elevator, Laundry in Building, Laund...
10        1.5         3                                                 []
15        1.0         0  [Doorman, Elevator, Fitness Center, Laundry in...
16        1.0         3  [Doorman, Elevator, Loft, Dishwasher, Hardwood...
18        2.0         3  [Fireplace, Laundry in Unit, Dishwasher, Hardw...
19        1.0         0  [Elevator, Laundry in Building, Dishwasher, Ha...
23        0.0         1                                  [Hardwood Floors]
32        3.0         3                       [Cats Allowed, Dogs Allowed]

#### ***ii. Удалите из столбца неиспользуемые символы ([,], ', ", и пробел).***

*после pd.read_json столбец features это не строка, а список Python. Поэтому для применения строковых методов нужно привести к строке.*

In [8]:
print(type(data_train["features"].iloc[0]))

<class 'list'>

In [9]:
data_train["features"].head(3)

4    [Dining Room, Pre-War, Laundry in Building, Di...
6    [Doorman, Elevator, Laundry in Building, Dishw...
9    [Doorman, Elevator, Laundry in Building, Laund...
Name: features, dtype: object

In [10]:
data_train["features"] = data_train["features"].astype(str)
data_train["features"].iloc[0]

"['Dining Room', 'Pre-War', 'Laundry in Building', 'Dishwasher', 'Hardwood Floors', 'Dogs Allowed', 'Cats Allowed']"

In [11]:
print(type(data_train["features"].iloc[0]))

<class 'str'>

In [12]:
for ch in ["[", "]", "'", '"', " "]:
    data_train["features"] = data_train["features"].str.replace(ch, "", regex=False)

data_train["features"].head(3)

4    DiningRoom,Pre-War,LaundryinBuilding,Dishwashe...
6    Doorman,Elevator,LaundryinBuilding,Dishwasher,...
9    Doorman,Elevator,LaundryinBuilding,LaundryinUn...
Name: features, dtype: str

In [13]:
print(
    "Всего пустых строк  в data_train датасете:", (data_train["features"] == "").sum()
)

Всего пустых строк  в data_train датасете: 3106

#### ***iii. Получите все значения в каждом списке и соберите результат в один большой список для всего набора данных. Для этого можно использовать DataFrame.iterrows().***

In [14]:
feature_list = []
for _, row in data_train.iterrows():
    if row["features"] != "":
        feature_list.extend(row["features"].split(","))

In [15]:
print("Длина списка:", len(feature_list))

Длина списка: 262377

In [16]:
feature_list[:5]

['DiningRoom', 'Pre-War', 'LaundryinBuilding', 'Dishwasher', 'HardwoodFloors']

#### ***iv. Сколько уникальных значений содержит список результатов?***

In [17]:
len(set(feature_list))

1529

#### ***v. Давайте познакомимся с новой библиотекой — Collections. С помощью этого пакета вы сможете эффективно получать количественную статистику по вашим данным.***

#### ***vi. Составьте список самых популярных функций из нашего обширного перечня и выберите 20 лучших на данный момент.***

In [18]:
from collections import Counter

In [19]:
feature_counts = Counter(feature_list)

In [20]:
top_20_pairs = feature_counts.most_common(20)
top_20_pairs

[('Elevator', 25375),
 ('HardwoodFloors', 23146),
 ('CatsAllowed', 23135),
 ('DogsAllowed', 21652),
 ('Doorman', 20479),
 ('Dishwasher', 20081),
 ('NoFee', 17793),
 ('LaundryinBuilding', 16082),
 ('FitnessCenter', 12989),
 ('Pre-War', 8971),
 ('LaundryinUnit', 8437),
 ('RoofDeck', 6417),
 ('OutdoorSpace', 5132),
 ('DiningRoom', 4890),
 ('HighSpeedInternet', 4223),
 ('Balcony', 2898),
 ('SwimmingPool', 2643),
 ('LaundryInBuilding', 2564),
 ('NewConstruction', 2504),
 ('Terrace', 2177)]

> **Заметка по оптимизации:**
> В рамках данного задания согласно ТЗ был выполнен пайплайн "Список -> Строка -> Очистка -> Разделение через iterrows()".
> Однако на реальных больших датасетах использование `iterrows()` является антипаттерном из-за низкой скорости работы циклов Python. В реальной практике этот же результат эффективнее и быстрее получить в две строки кода с помощью векторного метода `data_train["features"].explode()` и встроенного в Pandas метода `.str.join()`, что позволило бы избежать посимвольной очистки текста и сэкономило бы память.

ну и решается в пару строк как бонус все :)

In [21]:
# explode превращает DataFrame со списками в плоский ряд всех элементов
feature_list_2 = data_train_backup["features"].explode()

feature_counts_2 = Counter(feature_list_2)
top_20_pairs_2 = feature_counts_2.most_common(
    21
)  # т.к здесь не режу пустые строки, они в подсчете  и их  (nan, 3106)
top_20_pairs_2

[('Elevator', 25375),
 ('Hardwood Floors', 23146),
 ('Cats Allowed', 23135),
 ('Dogs Allowed', 21652),
 ('Doorman', 20479),
 ('Dishwasher', 20081),
 ('No Fee', 17793),
 ('Laundry in Building', 16082),
 ('Fitness Center', 12989),
 ('Pre-War', 8971),
 ('Laundry in Unit', 8437),
 ('Roof Deck', 6417),
 ('Outdoor Space', 5132),
 ('Dining Room', 4890),
 ('High Speed Internet', 4223),
 (nan, 3106),
 ('Balcony', 2898),
 ('Swimming Pool', 2643),
 ('Laundry In Building', 2564),
 ('New Construction', 2504),
 ('Terrace', 2177)]

***Ранее на каггле был другой датасет. Сейчас обновленный. Больше, чем был до этого.***

*пустые строки не учитываю на моменте сбора feature_list

#### ***vii. Если все правильно, вы должны получить следующие значения: 'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'.***

данные наименования фич совпадают с полученными (см.выше).

#### ***vi. Теперь создайте 20 новых признаков на основе 20 наиболее часто встречающихся значений: 1, если значение находится в столбце "Feature", в противном случае 0.***
*Now create 20 new features based on the top 20 values: 1 if the value is in the "Feature" column, otherwise 0.*

In [22]:
top_20 = [name for name, _ in top_20_pairs]
top_20[:3]

['Elevator', 'HardwoodFloors', 'CatsAllowed']

In [23]:
splits = data_train["features"].str.split(",")
type(splits)

pandas.Series

In [24]:
for feature in top_20:
    data_train[feature] = splits.apply(lambda lst: int(feature in lst))

In [25]:
data_train[top_20].head(3)

,Elevator,HardwoodFloors,CatsAllowed,DogsAllowed,Doorman,Dishwasher,NoFee,LaundryinBuilding,FitnessCenter,Pre-War,LaundryinUnit,RoofDeck,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace
4,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0
6,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0

#### ***ix. Расширьте наш набор признаков, добавив «ванные комнаты», «спальни», и создайте специальную переменную feature_list со всеми названиями признаков. Теперь у нас есть 22 значения. Все модели должны быть обучены на этих 22 признаках.***
Extend our feature set with 'bathrooms', 'bedrooms' and create a special variable feature_list with all feature names. Now we have 22 values. All models should be trained on these 22 features.

In [26]:
feature_list = top_20 + ["bathrooms", "bedrooms"]
print("Всего признаков:", len(feature_list))

Всего признаков: 22

### **4. Реализация моделей — Линейная регрессия**.

#### ***i. Реализуйте класс Python для алгоритма линейной регрессии с двумя основными методами — fit и predict. Используйте стохастический градиентный спуск (SGD) для поиска оптимальных весов модели. Для лучшего понимания рекомендуем реализовать отдельные версии алгоритма с аналитическим решением и нестохастическим градиентным спуском.***
implement a Python class for a linear regression algorithm with two basic methods — fit and predict. Use stochastic gradient descent (SGD) to find optimal model weights. For better understanding, we recommend implementing separate versions of the algorithm with the analytical solution and non-stochastic gradient descent under the hood.

#### ***1) Алгоритм с аналитическим решением.***

Аналитическое решение задачи регрессии.

$$
\boxed{
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf y
}
$$

#### ***Как решается обратная матрица на практике или почему обычно применяют метод pinv (а не inv) или lstsq, и почему det не диагностика в float64***

В этом проекте X = 22 признака + столбец единиц = 23×23,
матрица полноранговая → XᵀX обратима, np.linalg.inv работает; np.linalg.pinv
здесь страховка (на полноранговой матрице она совпадает с inv). Незаменимой
pinv становится при вырожденной или плохо обусловленной матрице: в ML_1
полином 10 степени от двух базовых признаков (квадратные признаки там остались
только проверкой гипотезы, в модель не пошли) дал 66 столбцов ранга 44 < 66 →
XᵀX сингулярна, np.linalg.inv бросила бы LinAlgError: Singular matrix.

**Почему det не диагностика в float64** (математически det = 0 ⇔ вырожденность):
* масштаб: det(cA) = cⁿ·det(A), при n = 66 отличная матрица даёт det ~1e-46
  или 1e+46 просто из-за масштаба;
* overflow/underflow: det легко уходит в нуль или бесконечность;
* det не показывает степень обусловленности: у катастрофически плохой матрицы
  |det| = 1 (напр., diag(1e10, 1e-10)).

Корректная диагностика — cond = σ_max/σ_min: теряется ~log10(cond) знаков
точности, у float64 запас ~16 знаков, значит cond ~1e16 даёт чистый шум при
det = 1; cond(XᵀX) = cond(X)², поэтому на XᵀX смотрят особенно строго.

**Почему pinv.** Псевдообратная (Мура–Пенроуза) считается через SVD: нулевые
и близкие к нулю сингулярные значения отбрасываются → работает на вырожденных
и плохо обусловленных матрицах, возвращая псевдорешение (least squares)
минимальной нормы. sklearn.LinearRegression решает через SVD
(scipy.linalg.lstsq), поэтому обучилась бы даже на ранге 44.

**Практическое правило:** проверять cond, а не det; решать через pinv/lstsq,
а не через inv.

In [27]:
# ones — столбец (вектор) из единиц длиной len(data_train):
# по одной единице на каждый объект, чтобы свободный коэффициент (bias)
# стал обычным весом при столбце-единице
# ones = np.ones((len(data_train), 1))
# ones = np.ones((len(data_train), 1))
# ones

In [28]:
# np.hstack([data_train, ones])#

In [29]:
class LinearRegressionAnalytic:
    """Линейная регрессия через аналитическое решение."""

    COND_THRESHOLD = 1e12

    def _prepare(self, X):
        """Приводит X к float и добавляет столбец единиц для bias."""
        X = np.asarray(X, dtype=float)
        return np.hstack([X, np.ones((len(X), 1))])

    def fit(self, X, y):
        """Обучает и сохраняет веса."""
        X_b = self._prepare(X)
        y = np.asarray(y, dtype=float)

        XtX = X_b.T @ X_b

        self.cond_ = np.linalg.cond(XtX)
        self.rank_ = np.linalg.matrix_rank(XtX)

        if self.cond_ > self.COND_THRESHOLD:
            warnings.warn(
                f"X^T X плохо обусловлена: cond={self.cond_:.3e}, "
                f"rank={self.rank_} из {XtX.shape[0]}. "
                "Коэффициенты могут быть неустойчивыми.",
                UserWarning,
            )

        self.w_ = np.linalg.pinv(XtX) @ X_b.T @ y

        return self

    def predict(self, X):
        """Возвращает прогноз."""
        return self._prepare(X) @ self.w_

    def fit_predict(self, X, y):
        """Обучает и возвращает прогноз."""
        return self.fit(X, y).predict(X)

In [30]:
X_train = data_train[feature_list]
y_train = data_train["price"]

In [31]:
lr_analytic = LinearRegressionAnalytic().fit(X_train, y_train)
y_pred_analytic = lr_analytic.predict(X_train)

print("вектор весов:", lr_analytic.w_.shape)

mae_analytic = round(mean_absolute_error(y_train, y_pred_analytic), 2)
rmse_analytic = round(mean_squared_error(y_train, y_pred_analytic) ** 0.5, 2)

print("MAE train:", mae_analytic)
print("RMSE train:", rmse_analytic)

вектор весов: (23,)
MAE train: 708.74
RMSE train: 1027.26

* **rank = 23** равен числу столбцов, то есть X^T X полноранговая и обратимая:
  строгой мультиколлинеарности и вырожденности нет. Все столбцы линейно независимы, аналитическое решение существует и единственно.

* ***$cond(X^T X) ≈ 483.44$*** — матрица хорошо обусловлена: cond(X) = sqrt(483.44) ≈ 22,
  потеря точности при решении системы порядка $lg483 ≈ 2.7$  десятичных знака
  из ~16 доступных у float64. Это ничтожно мало, порог предупреждения (1e12)
  не превышен, поэтому решение численно устойчиво и ему можно доверять.

#### ***2) Алгоритм с нестохастическим градиентным спуском***

#### Математика нестохастического (полного) градиентного спуска

Главное отличие от аналитической версии: там веса получались за одну операцию
обращения матрицы, здесь это итеративный процесс.

**Задача.** Минимизируем функцию потерь по всей обучающей выборке:

$$ L(w) = \frac{1}{2n} \|Xw - y\|^2 = \frac{1}{2} \cdot \underbrace{\frac{1}{n}\|Xw - y\|^2}_{MSE} $$

Коэффициент $\frac{1}{2n}$ состоит из двух частей с разными ролями:
* $\frac{1}{n}$ — нормировка: сумма квадратов ошибок становится средней,
  поэтому потеря и градиент не зависят от размера выборки, градиент равен
  среднему градиентов по объектам, и lr переносим между датасетами;
* $\frac{1}{2}$ — удобство дифференцирования: производная квадрата дает
  множитель 2, который сокращается с этой половинкой.

Минимизация $L$ равносильна минимизации MSE: константный множитель не меняет
положение минимума. В аналитическом решении коэффициент вообще не требовался
(уравнение $\nabla L = 0$ не меняется от умножения на константу), в спуске он
масштабирует шаг, и этот масштаб поглощается lr.

**Градиент.** В аналитическом решении потеря уже была раскрыта и
продифференцирована по вектору весов (там он обозначен $\boldsymbol{\beta}$,
здесь $w$; это один и тот же вектор):

$$ \frac{\partial L}{\partial \boldsymbol{\beta}} = -2 X^T \mathbf{y} + 2 X^T X \boldsymbol{\beta}
\quad \text{для } L = \|\mathbf{y} - X\boldsymbol{\beta}\|^2 \text{ без нормирующего множителя} $$

Там производную приравняли к нулю и решили $X^T X \boldsymbol{\beta} = X^T \mathbf{y}$
относительно весов, так получилось точное решение за один шаг. Здесь производную
к нулю не приравниваем, а используем как направление шага. С множителем
$\frac{1}{2n}$ это та же производная, умноженная на константу:

$$ \nabla_w L(w) = \frac{1}{2n}\left(2 X^T X w - 2 X^T \mathbf{y}\right) = \frac{1}{n} X^T (X w - \mathbf{y}) $$

Градиент указывает направление наибыстрейшего роста функции потерь, поэтому
шаг делаем в противоположную сторону. Именно этот градиент считает код класса:
grad = X_b.T @ residual / n.

**Обновление весов.** На каждой итерации:

$$ w \leftarrow w - lr \cdot \nabla_w L(w) = w - \frac{lr}{n} X^T (X w - \mathbf{y}) $$

Метод называется нестохастическим (full-batch), потому что градиент вычисляется
точно по всем n объектам выборки на каждом шаге, а не по одному случайному
объекту (SGD) и не по случайному подмножеству (mini-batch).

**Критерии остановки.** 

В классе используются два условия: $|\nabla L(w)|_2 < tol$
Если градиент стал достаточно мал, дальнейшие изменения весов будут небольшими, поэтому обучение можно завершить.

Второе условие - max_iter. Это максимальное число итераций и одновременно защита от слишком долгого обучения, если выбранный lr не позволяет быстро достичь заданного tol.

**Скорость сходимости.** На квадратичной функции спуск сходится линейно,
и число итераций зависит от числа обусловленности $cond(X^T X)$: чем оно больше,
тем медленнее спуск и тем сильнее «зигзаги» в узком овраге. Именно поэтому
класс внутри стандартизует признаки и цель: после стандартизации овраг
выравнивается, и один и тот же lr работает для всех координат.

In [32]:
class LinearRegressionGD:
    """Линейная регрессия через полный градиентный спуск.
    На каждой итерации градиент считается по всей обучающей выборке:
        L(w) = 1/(2n) * ||Xw - y||²
        grad = Xᵀ(Xw - y) / n
        w <- w - lr * grad
    """

    def __init__(self, lr=0.1, tol=1e-8, max_iter=10000):
        self.lr = lr
        self.tol = tol
        self.max_iter = max_iter

    def _prepare(self, X, fit=False):
        """Стандартизует X и добавляет столбец единиц для bias."""
        X = np.asarray(X, dtype=float)

        if fit:
            self.mean_ = X.mean(axis=0)
            self.std_ = X.std(axis=0)
            self.std_[self.std_ == 0] = 1.0

        X_s = (X - self.mean_) / self.std_

        return np.hstack([X_s, np.ones((len(X_s), 1))])

    def fit(self, X, y):
        y = np.asarray(y, dtype=float)

        self.y_mean_ = y.mean()
        self.y_std_ = y.std() or 1.0
        y_s = (y - self.y_mean_) / self.y_std_

        X_b = self._prepare(X, fit=True)
        n = len(y_s)

        self.w_ = np.zeros(X_b.shape[1])

        for iteration in range(self.max_iter):
            residual = X_b @ self.w_ - y_s
            grad = X_b.T @ residual / n

            self.w_ -= self.lr * grad

            if np.linalg.norm(grad) < self.tol:
                break

        self.n_iter_ = iteration + 1

        return self

    def predict(self, X):
        """Возвращает прогнозы в исходном масштабе y."""
        y_s = self._prepare(X) @ self.w_
        return y_s * self.y_std_ + self.y_mean_

    def fit_predict(self, X, y):
        return self.fit(X, y).predict(X)

-------------------------

**Что делает if np.linalg.norm(grad) < self.tol: break**

На текущей итерации grad - градиент функции потерь.

Его норма $|\nabla L(w)|_2$ показывает общий размер градиента.

Если $|\nabla L(w)|_2 < tol$, то градиент достаточно мал, поэтому следующий шаг

$\Delta w=-lr\cdot\nabla L(w)$ тоже будет небольшим.

break завершает цикл раньше, чем будет достигнут max_iter.
Если условие ни разу не сработало, обучение всё равно завершится на max_iter.

-----------------------

In [33]:
gd = LinearRegressionGD(
    lr=0.1,
    tol=1e-8,
    max_iter=10000,
).fit(X_train, y_train)

y_pred_gd = gd.predict(X_train)

print("итераций:", gd.n_iter_)

mae_gd = round(mean_absolute_error(y_train, y_pred_gd), 2)
rmse_gd = round(mean_squared_error(y_train, y_pred_gd) ** 0.5, 2)

print("MAE train:", mae_gd)
print("RMSE train:", rmse_gd)

итераций: 2024
MAE train: 708.74
RMSE train: 1027.26

#### ***3) Стохастический градиентный спуск (SGD)***

#### Математика стохастического градиентного спуска (SGD). лекция Балакирева. Добрый, добрый ИИ. (см.обсидиан)

В полном градиентном спуске градиент считается по всей выборке. В SGD на каждом
шаге используется только один случайно выбранный объект.

**Потеря на одном объекте:** $L_i(w)=\frac{1}{2}(x_i\cdot w-y_i)^2.$

Обозначим остаток: $r_i=x_i\cdot w-y_i.$

Тогда градиент потери одного объекта: $\nabla_w L_i(w)=r_i x_i.$

Поэтому один шаг SGD имеет вид: $w_{new}= w_{old}-lr_t\,r_i x_i.$

Каждый следующий шаг использует веса, полученные на предыдущем шаге.


**Почему используется один объект.** При случайном равновероятном выборе объекта градиент отдельного объекта является
оценкой полного градиента:

$$
\mathbb E_i[\nabla L_i(w)]
=
\frac1n\sum_{i=1}^{n}\nabla L_i(w)
=
\nabla L(w).
$$

Поэтому отдельные шаги SGD шумные, но в среднем направлены в сторону полного
градиента.

Один проход по всей выборке в случайном порядке называется **эпохой**.

Перемешивание объектов перед каждой эпохой позволяет не проходить выборку
каждый раз в одном и том же порядке.

**Расписание шага.** При постоянном lr шум отдельных градиентов сохраняется. Поэтому в SGD часто используют уменьшающийся шаг.

В классе доступны четыре варианта:

1) $\text{const:}\qquad lr_t=lr_0,$
2) $\text{linear:}\qquad
lr_t=lr_0\max\left(0,1-\frac{t}{T}\right),$
3) $\text{exp:}\qquad
lr_t=lr_0e^{-t/T},$
4) $\text{harmonic:}\qquad
lr_t=\frac{lr_0}{1+t/T}.$

Здесь t — номер глобального обновления, а T — горизонт расписания.
Если horizon=None, класс использует весь заданный бюджет обучения:
$T=max\_epochs\cdot n.$

**Останов обучения.** останавливаем по бюджету эпох (max_epochs). 
В отличие от полного GD, последовательность потерь отдельных объектов в SGD
шумная, поэтому критерий вида $L_t < tol$ не является хорошим универсальным критерием остановки. Кроме того, абсолютный уровень потерь зависит от данных. Поэтому сначала мы изучаем сам алгоритм SGD и простой критерий по числу эпох, а мониторинг сходимости рассматриваем отдельно.

**Мониторинг SGD.** Во время SGD точный функционал по всей выборке пересчитывать на каждом шаге
дорого: это требует прохода по всем объектам. Поэтому для мониторинга можно использовать экспоненциальное скользящее среднее (EMA) потерь отдельных объектов:

$Q_t=\lambda L_t+(1-\lambda)Q_{t-1}.$
где
$L_t = \frac{1}{2} (x_t \cdot w - y_t)^2$ - потеря на текущем объекте, 

а $\lambda = \frac{2}{N+1}$ задаёт условное окно памяти N

EMA не участвует в обновлении весов. Это только инструмент мониторинга. Оно сглаживает шумную последовательность потерь и позволяет наблюдать за процессом обучения. (это из лекции Балакирева - применять не стала)

---

**Таким образом разница трех подходов:**  

Analytic - получает веса сразу  
GD - повторяет полный градиент  
SGD - повторяет градиент одного объекта  

---

In [34]:
# недетерминированная версия алгоритма
class SimpleLinearRegressionSGD:
    """Линейная регрессия через через стохастический градиентный спуск SGD.
    Перед каждой эпохой объекты случайно перемешиваются.
    На каждом шаге:
        residual = x_i · w - y_i
        w -= lr * residual * x_i
    """

    def __init__(
        self,
        lr=0.01,
        max_epochs=50,
    ):
        self.lr = lr
        self.max_epochs = max_epochs

    def _prepare(self, X, fit=False):
        """Стандартизует X и добавляет столбец единиц для bias."""

        X = np.asarray(X, dtype=float)

        if fit:
            self.mean_ = X.mean(axis=0)
            self.std_ = X.std(axis=0)
            self.std_[self.std_ == 0] = 1.0

        X_s = (X - self.mean_) / self.std_

        return np.hstack([X_s, np.ones((len(X_s), 1))])

    def fit(self, X, y):
        """Обучает модель недетерминированным SGD."""

        y = np.asarray(y, dtype=float)

        # Стандартизация y
        self.y_mean_ = y.mean()
        self.y_std_ = y.std() or 1.0

        y_s = (y - self.y_mean_) / self.y_std_

        # Подготовка X
        X_b = self._prepare(X, fit=True)

        n = len(y_s)

        # Начальные веса
        self.w_ = np.zeros(X_b.shape[1])

        for epoch in range(self.max_epochs):
            # Создаём индексы и случайно перемешиваем их
            indices = np.arange(n)
            np.random.shuffle(indices)

            # Один проход по всей выборке
            for i in indices:
                x_i = X_b[i]

                residual = x_i @ self.w_ - y_s[i]

                self.w_ -= self.lr * residual * x_i

        self.n_epochs_ = self.max_epochs
        self.n_updates_ = self.max_epochs * n

        return self

    def predict(self, X):
        """Возвращает прогнозы в исходном масштабе y."""

        y_s = self._prepare(X) @ self.w_

        return y_s * self.y_std_ + self.y_mean_

    def fit_predict(self, X, y):
        """Обучает модель и возвращает прогнозы."""

        return self.fit(X, y).predict(X)

#### ***ii. Что такое детерминированная модель? Сделайте SGD детерминированным.***
What is determenistic model? Make SGD determenistic.

*Детерминированная модель при одинаковых входных данных и настройках всегда выдаёт одинаковый результат. В предыдущей реализации SimpleLinearRegressionSGD порядок объектов перемешивается без фиксированного seed, поэтому результаты обучения могут отличаться (пример ниже). Чтобы сделать SGD детерминированным, необходимо зафиксировать seed генератора случайных чисел.*

In [35]:
sgd_simple_model1 = SimpleLinearRegressionSGD()
sgd_simple_model2 = SimpleLinearRegressionSGD()

sgd_simple_model1.fit(X_train, y_train)
sgd_simple_model2.fit(X_train, y_train)

are_close = np.allclose(sgd_simple_model1.w_, sgd_simple_model2.w_)

print(f"Одинаковые веса: {'да' if are_close else 'нет'}")
print(
    "Максимальное различие:",
    np.max(np.abs(sgd_simple_model1.w_ - sgd_simple_model2.w_)),
)

Одинаковые веса: нет
Максимальное различие: 0.27499953085170903

In [36]:
weights_df = pd.DataFrame(
    {
        "Weights Model 1": sgd_simple_model1.w_,
        "Weights Model 2": sgd_simple_model2.w_,
        "Absolute Diff": np.abs(sgd_simple_model1.w_ - sgd_simple_model2.w_),
    }
)
print("Различие весов при двух запусках недетерминированного алгоритма SGD")
display(weights_df.head(5))

Различие весов при двух запусках недетерминированного алгоритма SGD

   Weights Model 1  Weights Model 2  Absolute Diff
0         0.078990         0.037721       0.041269
1        -0.097372        -0.078366       0.019006
2        -0.056128         0.000638       0.056766
3         0.057818         0.028958       0.028861
4         0.172962         0.226077       0.053115

***Для того чтобы результаты обучения модели были воспроизводимыми (детерминированными) от запуска к запуску:***

1. **Введен параметр** `random_state` (по умолчанию = 21) в конструктор класса.
2. **Создается объект-генератор случайных чисел** `rng = np.random.default_rng(self.random_state)` в методе `fit` перед циклами прохождения эпох.
3. **Генератор используется** на каждой эпохе для перемешивания индексов данных перед проходом по датасету с помощью `rng.permutation(n)`.

In [37]:
# детерминированнй алгоритм стохастического градиентного спуска
class LinearRegressionSGD:
    """Линейная регрессия через стохастический градиентный спуск.
    На каждом шаге используется один случайный объект:
        residual = x_i · w - y_i
        loss = 1/2 * residual^2
        w -= lr_t * residual * x_i
    Один проход по всей выборке в случайном порядке называется эпохой.
    """

    def __init__(
        self,
        lr=0.1,
        schedule="harmonic",
        horizon=None,
        max_epochs=50,
        random_state=21,
    ):
        self.lr = lr
        self.schedule = schedule
        self.horizon = horizon
        self.max_epochs = max_epochs
        self.random_state = random_state

    def _prepare(self, X, fit=False):
        """Стандартизует X и добавляет столбец единиц для bias."""
        X = np.asarray(X, dtype=float)

        if fit:
            self.mean_ = X.mean(axis=0)
            self.std_ = X.std(axis=0)
            self.std_[self.std_ == 0] = 1.0

        X_s = (X - self.mean_) / self.std_

        return np.hstack([X_s, np.ones((len(X_s), 1))])

    def _learning_rate(self, t, T):
        """Возвращает шаг lr_t для текущего обновления."""
        if self.schedule == "const":
            return self.lr

        if self.schedule == "linear":
            return self.lr * max(0.0, 1 - t / T)

        if self.schedule == "exp":
            return self.lr * np.exp(-t / T)

        if self.schedule == "harmonic":
            return self.lr / (1 + t / T)

        raise ValueError(
            "schedule должен быть одним из: 'const', 'linear', 'exp', 'harmonic'"
        )

    def fit(self, X, y):
        """Обучает модель стохастическим градиентным спуском."""
        y = np.asarray(y, dtype=float)

        self.y_mean_ = y.mean()
        self.y_std_ = y.std() or 1.0
        y_s = (y - self.y_mean_) / self.y_std_

        X_b = self._prepare(X, fit=True)
        n = len(y_s)

        T = self.horizon or self.max_epochs * n

        rng = np.random.default_rng(self.random_state)  # функция создающая генератор

        self.w_ = np.zeros(X_b.shape[1])

        t = 0

        for epoch in range(self.max_epochs):
            for i in rng.permutation(n):
                lr_t = self._learning_rate(t, T)

                x_i = X_b[i]
                residual = x_i @ self.w_ - y_s[i]
                loss = 0.5 * residual**2

                self.w_ -= lr_t * residual * x_i

                t += 1

        self.n_epochs_ = self.max_epochs
        self.n_updates_ = t

        return self

    def predict(self, X):
        """Возвращает прогнозы в исходном масштабе y."""
        y_s = self._prepare(X) @ self.w_
        return y_s * self.y_std_ + self.y_mean_

    def fit_predict(self, X, y):
        return self.fit(X, y).predict(X)

---
#### Доказательство детерминированности класса LinearRegressionSGD

In [133]:
sgd1 = LinearRegressionSGD(
    lr=0.01,
    schedule="harmonic",
    horizon=100000,
    max_epochs=50,
    random_state=21,
)

sgd2 = LinearRegressionSGD(
    lr=0.01,
    schedule="harmonic",
    horizon=100000,
    max_epochs=50,
    random_state=21,
)

sgd1.fit(X_train, y_train)
sgd2.fit(X_train, y_train)

print("Одинаковые веса:", np.allclose(sgd1.w_, sgd2.w_))

print("Максимальное различие:", np.max(np.abs(sgd1.w_ - sgd2.w_)))

Одинаковые веса: True
Максимальное различие: 0.0

---

In [38]:
sgd = LinearRegressionSGD(
    lr=0.01,
    schedule="harmonic",
    horizon=100000,
    max_epochs=50,
    random_state=21,
).fit(X_train, y_train)

y_pred_sgd = sgd.predict(X_train)

print("эпох:", sgd.n_epochs_, "| обновлений:", sgd.n_updates_)

mae_sgd = round(mean_absolute_error(y_train, y_pred_sgd), 2)
rmse_sgd = round(mean_squared_error(y_train, y_pred_sgd) ** 0.5, 2)

print("MAE train:", mae_sgd)
print("RMSE train:", rmse_sgd)

эпох: 50 | обновлений: 2417150
MAE train: 707.92
RMSE train: 1029.61

In [39]:
data = {
    "Method": ["Analytic", "Gradient Descent", "Stochastic GD"],
    "MAE": [mae_analytic, mae_gd, mae_sgd],
    "RMSE": [rmse_analytic, rmse_gd, rmse_sgd],
}

summary_df = pd.DataFrame(data).set_index("Method")
summary_df

                     MAE     RMSE
Method
Analytic          708.74  1027.26
Gradient Descent  708.74  1027.26
Stochastic GD     707.92  1029.61

#### ***iii. Определите коэффициент R² и реализуйте функцию для его вычисления.***
Define the R squared (R2) coefficient and implement a function to calculate it.

**Коэффициент детерминации** - это статистическая метрика, оценивающая долю дисперсии зависимой переменной, которая объясняется предсказаниями модели или насколько качественнее наша модель находит закономерности в данных по сравнению с наивным предсказанием в виде среднего арифметического ($\bar{y}$).

#### Математическая формула:

$$R^2 = 1 - \frac{SS_{res}}{SS_{tot}} = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2}$$

Где:
* $y_i$ — истинные значения целевого признака.
* $\hat{y}_i$ — предсказанные значения модели.
* $\bar{y}$ — среднее арифметическое истинных значений целевого признака ($\bar{y} = \frac{1}{n}\sum_{i=1}^{n}y_i$).
* $SS_{res}$ (*Residual Sum of Squares*) — сумма квадратов остатков (ошибок) модели.
* $SS_{tot}$ (*Total Sum of Squares*) — общая сумма квадратов отклонений от среднего значения (дисперсия целевой переменной).

#### Интерпретация значений:
* **$R^2 = 1.0$** — идеальная модель, предсказания полностью совпадают с реальными ответами.
* **$0 < R^2 < 1.0$** — модель работает лучше, чем предсказание среднего значения. Чем ближе к 1, тем выше качество.
* **$R^2 = 0.0$** — модель предсказывает на уровне среднего арифметического (не находит никакой структуры в данных).
* **$R^2 < 0.0$** — модель работает хуже, чем обычное среднее значение. В случае SGD это обычно сигнализирует о расхождении градиента (слишком большой шаг `lr`).

In [40]:
def r2_score(y_true, y_pred):
    """Вычисляет коэффициент детерминации R^2."""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    if ss_tot == 0:  # если y_true состоит из одинаковых констант
        return 0.0
    return 1.0 - (ss_res / ss_tot)

#### ***iv. С помощью вашего алгоритма сделайте прогнозы и оцените модель, используя метрики MAE, RMSE и R2.***
Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.

In [41]:
r2_sgd = r2_score(y_train, y_pred_sgd)

**Сводные метрики по самописному классу SGD на train выборке**

In [42]:
print(f"R2 = {round(r2_sgd, 2)}")
print(f"MAE = {summary_df.loc['Stochastic GD', 'MAE']}")
print(f"RMSE = {summary_df.loc['Stochastic GD', 'RMSE']}")

R2 = 0.58
MAE = 707.92
RMSE = 1029.61

#### ***v. Инициализируйте функцию LinearRegression() из sklearn.linear_model, обучите модель и выполните прогнозирование для обучающей и тестовой частей, как в предыдущем уроке.***
Initialize LinearRegression() from sklearn.linear_model, fit the model, and predict the training and test parts as in the previous lesson.

In [43]:
data_test[cols].head(5)

   bathrooms  bedrooms                                           features
0        1.0         1  [Elevator, Laundry in Building, Laundry in Uni...
1        1.0         2              [Pre-War, Dogs Allowed, Cats Allowed]
2        1.0         0              [Pre-War, Dogs Allowed, Cats Allowed]
3        1.0         2      [Hardwood Floors, Dogs Allowed, Cats Allowed]
5        1.0         1  [Roof Deck, Doorman, Elevator, Fitness Center,...

In [44]:
for feature in top_20:
    data_test[feature] = data_test["features"].apply(
        lambda lst: int(feature in [x.replace(" ", "") for x in lst])
    )

In [45]:
data_test[top_20].sum().head(3)

Elevator          38227
HardwoodFloors    34994
CatsAllowed       35052
dtype: int64

In [46]:
# feature_list = top_20 + ["bathrooms", "bedrooms"]
data_test[feature_list].head(3)

,Elevator,HardwoodFloors,CatsAllowed,DogsAllowed,Doorman,Dishwasher,NoFee,LaundryinBuilding,FitnessCenter,Pre-War,...,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace,bathrooms,bedrooms
0,1,1,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,0,1.0,1
1,0,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1.0,2
2,0,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1.0,0

In [47]:
y_test = data_test["price"]
X_test = data_test[feature_list]

In [48]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [49]:
y_pred_lr_train = lr.predict(X_train)
y_pred_lr_test = lr.predict(X_test)

In [50]:
mae_lr_train = round(mean_absolute_error(y_train, y_pred_lr_train), 2)
rmse_lr_train = round(mean_squared_error(y_train, y_pred_lr_train) ** 0.5, 2)
r2_lr_train = r2_score(y_train, y_pred_lr_train)

In [51]:
mae_lr_test = round(mean_absolute_error(y_test, y_pred_lr_test), 2)
rmse_lr_test = round(mean_squared_error(y_test, y_pred_lr_test) ** 0.5, 2)
r2_lr_test = r2_score(y_test, y_pred_lr_test)

In [52]:
y_pred_sgd_test = sgd.predict(X_test)

mae_sgd_test = round(mean_absolute_error(y_test, y_pred_sgd_test), 2)
rmse_sgd_test = round(mean_squared_error(y_test, y_pred_sgd_test) ** 0.5, 2)
r2_sgd_test = r2_score(y_test, y_pred_sgd_test)

#### ***vi. Сравните показатели качества и убедитесь, что разница невелика (между вашей реализацией и sklearn).***
Compare the quality metrics and make sure the difference is small (between your implementations and sklearn).

In [ ]:
def diff(m1, m2):
    diff = abs(m1 - m2)
    pct = (diff / max(m1, m2) * 100) if max(m1, m2) != 0 else 0
    return f"{pct:.2f}%"

In [132]:
print("Сравнение метрик Sklearn vs mySGD")
print("-" * 50)
print(f"{'':<12} {'Sklearn':>10} {'mySGD':>10} {'разница':>10}")
print("-" * 50)
print(
    f"{'R2_train:':<12} {r2_lr_train:>10.3f} {r2_sgd:>10.3f} {diff(r2_lr_train, r2_sgd):>10}"
)
print(
    f"{'R2_test:':<12} {r2_lr_test:>10.3f} {r2_sgd_test:>10.3f} {diff(r2_lr_test, r2_sgd_test):>10}"
)
print("-" * 50)
print(
    f"{'MAE_train:':<12} {mae_lr_train:>10.3f} {mae_sgd:>10.3f} {diff(mae_lr_train, mae_sgd):>10}"
)
print(
    f"{'MAE_test:':<12} {mae_lr_test:>10.3f} {mae_sgd_test:>10.3f} {diff(mae_lr_test, mae_sgd_test):>10}"
)
print("-" * 50)
print(
    f"{'RMSE_train:':<12} {rmse_lr_train:>10.3f} {rmse_sgd:>10.3f} {diff(rmse_lr_train, rmse_sgd):>10}"
)
print(
    f"{'RMSE_test:':<12} {rmse_lr_test:>10.3f} {rmse_sgd_test:>10.3f} {diff(rmse_lr_test, rmse_sgd_test):>10}"
)

Сравнение метрик Sklearn vs mySGD
--------------------------------------------------
                Sklearn      mySGD    разница
--------------------------------------------------
R2_train:         0.580      0.578      0.33%
R2_test:          0.579      0.577      0.30%
--------------------------------------------------
MAE_train:      708.740    707.920      0.12%
MAE_test:       709.900    709.240      0.09%
--------------------------------------------------
RMSE_train:    1027.260   1029.610      0.23%
RMSE_test:     1021.210   1023.310      0.21%

#### ***vii. Сохраните метрики, как и в предыдущем уроке, в таблице со столбцами model, train, test для таблицы MAE, таблицы RMSE и коэффициента R2.***
Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

In [55]:
result_MAE = pd.DataFrame(columns=["model", "train", "test"])
result_RMSE = pd.DataFrame(columns=["model", "train", "test"])
result_R2 = pd.DataFrame(columns=["model", "train", "test"])

In [56]:
result_MAE.loc[0] = ["linear_regressionSklearn", mae_lr_train, mae_lr_test]
result_MAE.loc[len(result_MAE)] = ["linear_regression_mySGD", mae_sgd, mae_sgd_test]

print("Итоговая таблица result_MAE")
print("-" * 45)
print(result_MAE)

Итоговая таблица result_MAE
---------------------------------------------
                      model   train    test
0  linear_regressionSklearn  708.74  709.90
1   linear_regression_mySGD  707.92  709.24

In [57]:
result_RMSE.loc[0] = ["linear_regressionSklearn", rmse_lr_train, rmse_lr_test]
result_RMSE.loc[len(result_RMSE)] = ["linear_regression_mySGD", rmse_sgd, rmse_sgd_test]

print("Итоговая таблица result_RMSE")
print("-" * 45)
print(result_RMSE)

Итоговая таблица result_RMSE
---------------------------------------------
                      model    train     test
0  linear_regressionSklearn  1027.26  1021.21
1   linear_regression_mySGD  1029.61  1023.31

In [58]:
result_R2.loc[0] = ["linear_regressionSklearn", r2_lr_train, r2_lr_test]
result_R2.loc[len(result_RMSE)] = ["linear_regression_mySGD", r2_sgd, r2_sgd_test]

print("Итоговая таблица result_R2")
print("-" * 45)
print(result_R2)

Итоговая таблица result_R2
---------------------------------------------
                      model     train      test
0  linear_regressionSklearn  0.580269  0.578839
2   linear_regression_mySGD  0.578351  0.577099

### **5. Реализация моделей с регуляризацией —  Ridge, Lasso, ElasticNet** 
Regularized models implementation - Ridge, Lasso, ElasticNet.

#### ***i. Реализуйте алгоритмы Ridge, Lasso и ElasticNet: расширьте функцию потерь с помощью L2, L1 и обеих регуляризаций соответственно.***
Implement Ridge, Lasso, ElasticNet algorithms: extend the loss function with L2, L1 and both regularizations accordingly.

***Ridge (L2) Функция потерь:***   $L_{\text{Ridge}}(w) = \frac{1}{2n}\|Xw-y\|_2^2 + \frac{\alpha}{2}\|w\|_2^2$

***Градиент регуляризационной части:*** $\nabla R(w) = w$

***Полный градиент:***  $\nabla L_{\text{Ridge}}(w) = \frac{1}{n}X^T(Xw-y) + \alpha w$

***Обновление весов:***$w^{(t+1)} = w^{(t)} - \eta \left[ \frac{1}{n}X^T(Xw-y) + \alpha w \right]$

---

***Lasso (L1) Функция потерь:*** $L_{\text{Lasso}}(w) = \frac{1}{2n}\|Xw-y\|_2^2 + \alpha\|w\|_1$

***Градиент регуляризационной части:*** $\nabla R(w) = \operatorname{sign}(w)$

***Полный градиент:***  $\nabla L_{\text{Lasso}}(w) = \frac{1}{n}X^T(Xw-y) + \alpha \operatorname{sign}(w)$

***Обновление весов:***     $w^{(t+1)} = w^{(t)} - \eta \left[ \frac{1}{n}X^T(Xw-y) + \alpha \operatorname{sign}(w) \right]$

---

***ElasticNet (L1 + L2) Функция потерь:***  $L_{\text{EN}}(w) = \frac{1}{2n}\|Xw-y\|_2^2 + \alpha \left( \rho \|w\|_1 + \frac{1-\rho}{2} \|w\|_2^2 \right)$

***Градиент регуляризационной части:*** $\nabla R(w) = \rho \operatorname{sign}(w) + (1-\rho) w$

***Полный градиент:***  $\nabla L_{\text{EN}}(w) = \frac{1}{n}X^T(Xw-y) + \alpha \left( \rho \operatorname{sign}(w) + (1-\rho) w \right)$

***Обновление весов:*** $
w^{(t+1)} = w^{(t)} - \eta \left[ \frac{1}{n}X^T(Xw-y) + \alpha \left( \rho \operatorname{sign}(w) + (1-\rho) w \right) \right]$

*Здесь $\rho$ (l1_ratio) - доля L1-регуляризации, $0 \le \rho \le 1$. Крайние случаи: $\rho=1$ - чистый Lasso, $\rho=0$ - чистый Ridge.*

---

* в класс буду передавать через параметры ridge, lasso, elasticnet (градиент = alpha * (l1_ratio * np.sign(w) + (1 - l1_ratio) * w))

In [ ]:
# не забыть что  bias штрафовать не нужно!!
# w_reg = self.w_.copy()
# w_reg[-1] = 0

#### ***ii. С помощью вашего алгоритма сделайте прогнозы и оцените модель, используя метрики MAE, RMSE и R2.***
Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.

#### ***iii. Инициализируйте функции Ridge(), Lasso() и ElasticNet() из sklearn.linear_model, обучите модель и сделайте прогнозы для обучающей и тестовой выборок, как в предыдущем уроке.***
Initialize Ridge(), Lasso(), and ElasticNet() from sklearn.linear_model, fit the model, and make predictions for the training and test samples as in the previous lesson.

#### ***iv. Сравните показатели качества и убедитесь, что разница невелика (между вашими реализациями и sklearn).***
Compare quality metrics and make sure the difference is small (between your implementations and sklearn).

#### ***v. Сохраните метрики, как и в предыдущем уроке, в таблице со столбцами model, train, test для таблицы MAE, таблицы RMSE и коэффициента R2.***
Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

### **6. Нормализация признаков** 
Feature normalization

#### ***i. Сначала приведите несколько примеров того, почему и где нормализация признаков является обязательной, и наоборот.***
First, write several examples of why and where feature normalization is mandatory and vice versa.

#### ***ii. Рассмотрим первый из классических методов нормализации — MinMaxScaler. Запишите математическую формулу для этого метода.***
Let's consider the first of the classical normalization methods — MinMaxScaler. Write a mathematical formula for this method.

#### ***iii. Реализуйте собственную функцию или класс для нормализации признаков с помощью MinMaxScaler.***
Implement your own function or class for MinMaxScaler feature normalization.

#### ***iv. Инициализируйте функцию MinMaxScaler() из sklearn.preprocessing.***
Initialize MinMaxScaler() from sklearn.preprocessing.

#### ***v. Сравните результаты нормализации признаков, полученные с помощью вашего собственного метода и метода sklearn.***
Compare the feature normalization with your own method and with sklearn.

#### ***vi. Повторите шаги с b по e для другого метода нормализации — StandardScaler.***
Repeat the steps from b to e for another normalization method StandardScaler.

### **7. Обучите пользовательские модели и модели sklearn на нормализованных данных.** 
Fit custom and sklearn models with normalized data

#### ***i. Для всех моделей — линейной регрессии, гребневой регрессии, лассо и ElasticNet — используйте MinMaxScaler..***
Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with MinMaxScaler.

#### ***ii. Для построения всех моделей — линейной регрессии, гребневой регрессии, лассо и ElasticNet — используйте StandardScaler..***
Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with StandardScaler.

#### ***iii. Добавьте все результаты в наш датафрейм с метриками по образцам.***
Add all results to our dataframe with metrics on samples.

### **8. Переобученные модели** 
Overfit models

#### ***i. Давайте рассмотрим переобученную модель на практике. Из теории известно, что полиномиальная регрессия легко переобучается. Поэтому давайте создадим простой пример и посмотрим, как работает регуляризация в реальной жизни..***
Let's look at an overfitted model in practice. From theory, you know that polynomial regression is easy to overfit. So let's create a toy example and see how regularization works in real life.

#### ***ii. На предыдущем уроке мы создали полиномиальные признаки 10-й степени. Здесь мы повторяем эти шаги из предыдущего урока, помня, что у нас есть только 2 основных признака — «ванные комнаты» и «спальни»..***
In the previous lesson, we created polynomial features with degree 10. Here we repeat these steps from the previous lesson, remembering that we have only 2 basic features — 'bathrooms' and 'bedrooms'.

#### ***iii. Обучите и настройте все реализованные нами алгоритмы — линейную регрессию, Ridge, Lasso и ElasticNet — на наборе полиномиальных признаков..***
And train and fit all our implemented algorithms — Linear Regression, Ridge, Lasso, and ElasticNet — on a set of polynomial features.

#### ***iv. Сохраните результаты метрик качества в результирующем датафрейме.***
Store the results of the quality metrics in the result dataframe.

#### ***v. Проанализируйте результаты и выберите лучшую модель, исходя из вашего мнения..***
Analyze the results and select the best model according to your opinion.

#### ***vi. Кроме того, попробуйте разные значения параметра альфа-регуляризации в алгоритмах, выберите оптимальный и проанализируйте результаты..***
Additionally try different alpha parameters of regularization in algorithms, choose the best one and analyze results.

### **9. Наивные модели** 
Native models

#### ***i. Вычислите среднее и медианное значения показателей из предыдущего урока и добавьте результаты в итоговую таблицу данных.***
Calculate the mean and median metrics from the previous lesson and add the results to the final dataframe.

### **10. Сравните результаты** 
Compare results

#### ***i. Распечатайте итоговые таблицы.***
Print your final tables

#### ***ii. Какая модель лучшая?***
What is the best model?

#### ***iii. Какая модель наиболее стабильна?.***
Which is the most stable model?

### **11. Дополнительное задание** 
Addition task

#### ***i. Существуют некоторые приемы работы с целевой переменной для улучшения качества модели. Если распределение имеет «тяжелый хвост», можно использовать монотонную функцию для «улучшения» распределения. На практике можно использовать логарифмические функции. Мы рекомендуем выполнить это упражнение и сравнить результаты. Но не забудьте выполнить обратное преобразование, если хотите сравнить метрики..***
There are some tricks with the target variable for better model quality. If we have a distribution with a heavy tail, you can use a monotone function to "improve" the distribution. In practice, you can use logarithmic functions. We recommend that you do this exercise and compare the results. But don't forget to do the inverse transformation if you want to compare metrics.

#### ***ii. Следующий важный момент — выбросы. Угол линии линейной регрессии сильно зависит от выбросов. И часто эти точки следует удалять только из обучающих данных. Необходимо объяснить, почему они были удалены только из обучающей выборки. Мы рекомендуем выполнить это упражнение и сравнить результаты..***
The next trick is outliers. The angle of the linear regression line depends strongly on outliers. And often you should remove these points from !allert! only training data. You should explain why they were removed from the training sample only. We recommend that you do this exercise and compare the results.

#### ***iii. Также полезным упражнением будет реализация алгоритма линейной регрессии с пакетным и мини-пакетным обучением или аналитическим решением .***
It will also be a useful exercise to implement a linear regression algorithm with batch and mini-batch training or analytical solution.